---
title: "Github Pages Tutorial"
author: "Ted Laderas, Eric Leung, and Robin Champieux"
date: "4/5/2017"
output:
  slidy_presentation: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## What is GitHub Pages?

GitHub Pages is a built-in system that allows you to build websites directly from a GitHub Repository.

There are two kinds of GitHub pages:

+ Personal websites (associated with an account)
+ Repository Specific Websites (webpages for software)

## What You Need for Today

You don't need to know how to code to setup a GitHub page. We'll learn some Markdown basics

+ GitHub Account
+ GitHub Desktop
+ Text Editor (Sublime, Atom, TextEdit)
+ File Manager (to rename files)
+ Something to say
+ Pictures (optional)

## Let's Make a Personal Webpage

If you have a GitHub account with USERNAME, you can serve a webpage directly from USERNAME.github.io. For example: http://laderast.github.io

You first need to create a repository with that name. From GitHub Desktop, click the "+" symbol, and create a new repository. 
[maybe clone a website first]

When you've created the repository, "publish" it to GitHub.

Once you've published the repository, try your personal webpage: http://USERNAME.github.io

## File Structure



## Markdown and Index.md

Anything with index.md will be automatically translated and served as a webpage.

Using Jekyll, you can add header and footers and other templating features, standardizing the look of your pages as you like.

One thing to remember is when your output is html, you can embed HTML tags, which is especially useful for embedding images, since you can adjust image size directly within the tag.

## Let's Add Some Links



## Let's Add an Image

## Add a Blog Entry

Your current repository is setup for blog entries. 

## Modifying the Menu



## GitHub Pages

Another nice use of Markdown is for authoring websites. You can do this really easily with GitHub pages.

GitHub Pages uses an HTML translation engine called *Jekyll*, which is written in Ruby to translate Markdown into HTML. You don't really need to know about it, unless you want to use the templating in Jekyll to build something like a blog.

One benefit to using Jekyll is that it's a relatively lightweight way to manage a blog without a more complicated, database-using, content management system. Because of this, it's relatively portable and you can easily take your documents with you if you decide to migrate to another system.

## Markdown and GitHub pages

Any markdown file that has an .markdown or .md extension will automatically be processed by GitHub and served as a html page. For example: https://github.com/laderast/magic-of-markdown/blob/master/magic-of-markdown.md

If you want to make a webpage for your code, you need to create a branch called `gh-pages` and put the markdown files in there. I believe you can also just place html files as well.

## Jekyll File Structure

If you're interested in setting up a blog or more complicated site, you'll have to learn a little bit about Jekyll and the [liquid templating](http://jekyllrb.com/docs/templates/) language.

You can download Jekyll by itself to see how it transforms markdown files, but to get started with a blog or pages, it's actually way easier to [clone Poole](https://github.com/poole/poole), which gives you the basic file structure that you can use to serve the GitHub pages.
